# ansible-cmdb is yet another utility to generate the data!
# https://itnext.io/create-a-host-inventory-in-a-minute-with-ansible-c7bf251166d9
---
- hosts: all
  become: no
  vars:
    output_file: os.csv
  tasks:
    - block:
        # For permission setup.
        - name: get current user
          command: whoami
          register: whoami
          run_once: yes

        - name: clean file
          copy:
            dest: "{{ output_file }}"
            content: 'hostname,distribution,version,release,mem_total,cores'
            owner: "{{ whoami.stdout }}"
          run_once: yes

        - name: fill os information
          lineinfile:
            path: "{{ output_file }}"
            line: "{{ ansible_hostname }},\
              {{ ansible_distribution }},\
              {{ ansible_distribution_version }},\
              {{ ansible_distribution_release }}, \
			  {{ ansible_memtotal_mb }}, \
			  {{ ansible_processor_cores }}"
          # Tries to prevent concurrent writes.
          throttle: 1
      delegate_to: localhost
...
